@url = https://miniature-bassoon-w6w7jpwwrj9hggp4-8080.app.github.dev/alunos

POST {{url}}
Content-Type: application/json

{
    "nome" : "Daniel", 
    "idade" : 20
}

###
GET {{url}}

###
PUT {{url}}/1
Content-Type: application/json

{
    "nome" : "Erick Cirico",
    "idade" : 21 
}

###
DELETE {{url}}/2

###
GET {{url}}/1
