@url = https://miniature-bassoon-w6w7jpwwrj9hggp4-8080.app.github.dev/alunos

POST {{url}}
Content-Type: application/json

{
    "nome" : "Rosangela", 
    "idade" : 50
}

###
GET {{url}}

###
PUT {{url}}/52
Content-Type: application/json

{
    "idade" : 18 
}

###
DELETE {{url}}/52

###
GET {{url}}/102
