@url = http://localhost:8080/tarefas

POST {{url}}
Content-Type: application/json

{
    "id" : 2,
    "descricao" : "Regar a planta!!!!! (as 09h)" 
}

###
GET {{url}}

###
PUT {{url}}/4
Content-Type: application/json

{
    "descricao" : "Essa tarefa existe?" 
}
###
DELETE {{url}}/3
